### ISSUE TITLE
calling sem-add in quick succession overwrites updates

### ISSUE THREAD

**Issue by jevonearth** [gilt/schema-evolution-manager#19]
I'm porting old sql schema changes to sem. I scripted the process and called sem-add on each change. 

```
sem-add ./update-002.sql ; git commit -m "db schema update 002"
sem-add ./update-003.sql ; git commit -m "db schema update 003"
sem-add ./update-004.sql ; git commit -m "db schema update 004"
.
.
sem-add ./update-364.sql ; git commit -m "db schema update 364"
sem-add ./update-365.sql ; git commit -m "db schema update 365"
```

I got files in the scripts directory:

```
20150423-205830.sql
20150423-205831.sql
20150423-205832.sql
20150423-205833.sql
20150423-205834.sql
20150423-205835.sql
20150423-205836.sql
20150423-205837.sql
20150423-205838.sql
20150423-205839.sql
20150423-205840.sql
20150423-205841.sql
20150423-205842.sql
20150423-205843.sql
20150423-205844.sql
20150423-205845.sql
20150423-205846.sql
20150423-205847.sql
20150423-205848.sql
```

19 files, versus 365 files added using `sem-add`. Inspecting the files, I see that there are gaps in my 1-365 sequence.

Using time-stamps is too a naïve method in this case. I will work around by sleeping for a second between executing `sem-add`.

ps. Thanks for this tool!

**Comment by Seanstoppable** [comment]
That is a good point. Minimally we should check for the existence of a file and throw an error to at least expose this edge case. Alternately, append an incrementing number at the end in the event of conflicts, to preserve the timestamp ordering but prevent the overwrites.

**Comment by mbryzek** [comment]
Thanks so much for reporting!

One possible implementation here: https://github.com/gilt/schema-evolution-manager/pull/20

This will generate a suffix on duplicate filenames. So filenames will look like:

20121113-150902.sql
20121113-150902.z1001.sql
20121113-150902.z1002.sql

the "z" is there to enforce lexicographic sorting

If you have 10k files / second, you'll get an error.

Curious what you think about this approach ... one alternative is to inject the sleep(1) into sem-add itself when there is a duplicate. That would avoid needing the .zxxxx suffixes.

**Comment by jevonearth** [comment]
I did a quick test, and this looks to work well. The suffix is fine. Using sleep isn't that nice IMO, it adds 365 seconds of waiting in my specific use-case. :)

**Comment by perl2ruby** [comment]
Looks like we can use milli, micro, nano or pico for strftime:
<pre>
ruby -e '{ "milli" => "%3N", "micro" => "%6N", "nano" => "%9N", "pico" => "%12N"}.each_pair {|k,v| puts %Q{With #{k}: #{Time.now.strftime("%Y%m%d%H%M%S_" + v)}}}'
With milli: 20150424143431_116
With micro: 20150424143431_116354
With nano: 20150424143431_116372000
With pico: 20150424143431_116378000000
</pre>

**Comment by mbryzek** [comment]
Thanks all! have merged the PR and published a new release -
https://github.com/gilt/schema-evolution-manager
